spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: customer_route
          uri: lb://customer-service
          predicates:
            - Path=/api/v1/customers/**
        - id: reservation_route
          uri: lb://reservation-service
          predicates:
            - Path=/api/v1/reservations/**
        - id: hotel_route
          uri: lb://hotel-service
          predicates:
            - Path=/api/v1/hotels/**
        - id: payment_route
          uri: lb://payment-service
          predicates:
            - Path=/api/v1/payments/**
        - id: notification_route
          uri: lb://notification-service
          predicates:
            - Path=/api/v1/notifications/**
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://host.docker.internal:8761/eureka}
  instance:
    preferIpAddress: true
