spring:
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: myGroup
    producer:
      properties:
        spring:
          json:
            add:
              type:
                headers: false
  datasource:
    username: sa
    url: jdbc:h2:mem:customerdb
    driverClassName: org.h2.Driver
    password: password
  h2:
    console:
      enabled: 'true'
  application:
    name: customer-service
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
eureka:
  instance:
    preferIpAddress: 'true'
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka
server:
  port: '9001'
